version: '3'

services:
  home-assistant:
    image: homeassistant/home-assistant:0.87.1
    container_name: hass
    restart: unless-stopped
    volumes:
      - ./hass:/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/hosts:/etc/hosts:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    network_mode: host
      
  mqtt:
    image: eclipse-mosquitto:1.5.5
    container_name: MQTT
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/log:/mosquitto/log
      - /etc/localtime:/etc/localtime:ro
      - /etc/hosts:/etc/hosts:ro

  mariadb:
    image: mariadb:10.4
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: Zv#ogsZKXup2DNLGW*tu
      MYSQL_DATABASE: hass
      MYSQL_USER: admin
      MYSQL_PASSWORD: Zv#ogsZKXup2DNLGW*tu
    network_mode: host    
    restart: unless-stopped
    volumes:
      - ./mariadb:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/hosts:/etc/hosts:ro

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - TZ=Europe/Amsterdam
    network_mode: host    
    restart: unless-stopped
    volumes:
      - ./sonarr/config:/config
      - ./../Plex Library/SERIES:/tv
      - ./../Downloads/_DOWNLOADED:/downloads
      - /etc/localtime:/etc/localtime:ro
      - /etc/hosts:/etc/hosts:ro
      
  couchpotato:
    image: linuxserver/couchpotato
    container_name: couchpotato
    environment:
      - TZ=Europe/Amsterdam
      - UMASK_SET=022
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./couchpotato:/config
      - ./../Downloads/_DOWNLOADED:/movies
      - ./../Downloads/NZBs:/downloads
      - /etc/localtime:/etc/localtime:ro
      - /etc/hosts:/etc/hosts:ro
      
  sabnzbd:
    image: linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - TZ=Europe/Amsterdam
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./sabnzbd:/config
      - ./../Downloads/_DOWNLOADED:/downloads
      - ./../Downloads/_DOWNLOADING:/incomplete-downloads
      - /etc/localtime:/etc/localtime:ro
      - /etc/hosts:/etc/hosts:ro

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    environment:
      - TZ=Europe/Amsterdam
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./jackett:/config
      - ./../Downloads/NZBs:/downloads
      - /etc/localtime:/etc/localtime:ro
      - /etc/hosts:/etc/hosts:ro 
