version: '3.2'

services:
  home-assistant:
    image: homeassistant/home-assistant:0.109.6
    container_name: hass
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./hass:/config
      - /etc/localtime:/etc/localtime:ro
      - /etc/hosts:/etc/hosts:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/ttyUSB0:/dev/ttyUSB0

  nodered:
    image: nodered/node-red:1.0.4
    container_name: nodered
    restart: unless-stopped
    ports:
      - 1880:1880
    user: root
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ./nodered:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/TZ:/etc/timezone:ro
      - /etc/hosts:/etc/hosts:ro

  esphome:
    image: esphome/esphome:dev
    container_name: esphome
    restart: unless-stopped
    ports:
      - 6052:6052
    volumes:
      - ./esphome:/config:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/hosts:/etc/hosts:ro

  mqtt:
    image: eclipse-mosquitto:1.5
    container_name: MQTT
    restart: unless-stopped
    ports:
      - 1883:1883
    volumes:
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/log:/mosquitto/log
      - /etc/localtime:/etc/localtime:ro
      - /etc/hosts:/etc/hosts:ro

  influxdb:
    image: influxdb:1.7
    container_name: influxdb
    restart: unless-stopped
    ports:
      - 8086:8086
    volumes:
      - ./influxdb:/var/lib/influxdb
      - /etc/localtime:/etc/localtime:ro
      - /etc/hosts:/etc/hosts:ro
    environment:
      - INFLUXDB_DB=hass

  grafana:
    image: grafana/grafana:6.1.6
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    user: "1026"
    depends_on:
      - influxdb
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_AUTH_BASIC_ENABLED=false

  mariadb:
    image: mariadb:10.4
    container_name: mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: <REDACTED>
      MYSQL_DATABASE: hass
      MYSQL_USER: <REDACTED>
      MYSQL_PASSWORD: <REDACTED>
    volumes:
      - ./mariadb:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/hosts:/etc/hosts:ro

  postgres:
    image: mariadb:10.4
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5555:3306
    environment:
      MYSQL_ROOT_PASSWORD: dsmrreader
      MYSQL_DATABASE: dsmrreader
      MYSQL_USER: dsmrreader
      MYSQL_PASSWORD: dsmrreader
    volumes:
      - ./postgres:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/hosts:/etc/hosts:ro

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    ports:
      - 8989:8989
    volumes:
      - ./sonarr/config:/config
      - ./../Plex Library/SERIES:/tv
      - ./../Downloads/_DOWNLOADED:/downloads
      - /etc/localtime:/etc/localtime:ro
      - /etc/hosts:/etc/hosts:ro
    environment:
      - TZ=Europe/Amsterdam

  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - ./sabnzbd:/config
      - ./../Downloads/_DOWNLOADED:/downloads
      - ./../Downloads/_DOWNLOADING:/incomplete-downloads
      - /etc/localtime:/etc/localtime:ro
      - /etc/hosts:/etc/hosts:ro

  calibre:
    image: linuxserver/calibre-web:latest
    container_name: calibre-web
    restart: unless-stopped
    ports:
      - 8083:8083
    environment:
      - TZ=Europe/Amsterdam
      - PUID=1026
      - PGID=1026
    volumes:
      - ./calibre:/config
      - ./../eBooks/Calibrebibliotheek:/books
      - /etc/localtime:/etc/localtime:ro
      - /etc/hosts:/etc/hosts:ro
